name: Node.js CI/CD

on:
  push:
    branches: ["electrostoremain"]
  pull_request:
    branches: ["electrostoremain"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: |
          touch .env
          echo "${{ secrets.ELECTROSHOP_PROD }}" > .env
